# Load ANSI color codes into the shell.
autoload -Uz colors && colors

# Initialize the completion system.
autoload -Uz compinit && compinit

zstyle ':completion:*' verbose true

zstyle ':completion:*' list-dirs-first true

zstyle ':completion:*' menu true

# Initialize the version control awareness system.
autoload -Uz vcs_info

# Enable the git backend for vcs_info.
zstyle ':vcs_info:*' enable git

# Detect changes in the local repository so %c and %u will work.
zstyle ':vcs_info:git:*' check-for-changes true

# Formatting for %c (staged changes) format string.
zstyle ':vcs_info:git*' stagedstr "%{$fg[green]%}+%{$reset_color%}"

# Formatting for %u (unstaged changes) format string.
zstyle ':vcs_info:git*' unstagedstr "%{$fg[red]%}~%{$reset_color%}"

# Format prompt string used during an "action" like a rebase or merge.
zstyle ':vcs_info:git*' actionformats ":%{$fg[magenta]%}%b%{$reset_color%}%u%c:%{$fg[cyan]%}%a%{$reset_color%}"

# Normal prompt format string.
zstyle ':vcs_info:git*' formats ":%{$fg[magenta]%}%b%{$reset_color%}%u%c"

# Change directory by typing directory name if it's not a command.
setopt auto_cd 

# Make cd push the old directory onto the directory stack.
setopt auto_pushd

# Add commands to history as they are entered, don't wait for shell to exit.
setopt inc_append_history

# Allow parameter expansion, command substitution, and arithmetic expansion to
# happen in prompts.
setopt prompt_subst

# Executed before each prompt.
precmd() {
  vcs_info
}

PROMPT='%{$fg[blue]%}%~%{$reset_color%}${vcs_info_msg_0_}%# '

alias ..='cd ..'
alias ll='ls -lGh --color=auto'
alias ls='ls -Gh --color=auto'

# Tidy up and truncate output filenames to avoid hitting filename size limitations.
alias vdl='youtube-dl -o "%(title).150s-%(id)s.%(ext)s" --restrict-filenames'

#ruby
export PATH="$HOME/.rbenv/bin:$PATH"
# Lazy-loading for rbenv
rbenv() {
  # command forces the argument to run as an external command
  # instead of a function or builtin
  eval "$(command rbenv init -)"
  rbenv $@
}

# python
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
# Lazy-loading for pyenv
pyenv() {
  eval "$(command pyenv init -)"
  pyenv $@
}
export PATH="$HOME/.poetry/bin:$PATH"

# rust
export PATH="$HOME/.cargo/bin:$PATH"

# n (node version manager)
export N_PREFIX="$HOME/.n"
export PATH="$N_PREFIX/bin:$PATH"

# go
export GOPATH="$HOME/go"
export PATH="$GOPATH/bin:$PATH"
export PATH="/usr/local/go/bin:$PATH"

# xdg dirs
export PATH="$HOME/.local/bin:$PATH"

# Source site-local alias configuration.
[[ -f ~/aliases.sh ]] && source ~/.aliases.sh

# Source site-local path configuration.
[[ -f ~/.path.sh ]] && source ~/.path.sh

# Source site-local functions.
[[ -f ~/.funcs.sh ]] && source ~/.funcs.sh

source <(antibody init)
antibody bundle < "$HOME/.zsh_plugins.txt"
